server:
  port: 9001

spring:
  application:
    name: department-service
  config:
    import: optional:configserver:http://localhost:9296
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true