server:
  port: 9091

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: departmentCircuitBreaker
                fallbackUri: forward:/department-fallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s
    instances:
      department:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 8s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
  timelimiter:
    configs:
      default:
        timeoutDuration: 4s
        cancelRunningFuture: false
    instances:
      department:
        timeoutDuration: 3s
        cancelRunningFuture: false