server:
  port: 9002

spring:
  application:
    name: department-service
  config:
    import: optional:configserver:http://localhost:9296
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
