server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      override-system-properties: true
      server:
        git:
          uri: https://github.com/tonilxm/spring-ms-full.git
          clone-on-start: true
          search-paths:
            config-server/src/main/resources/config
      label: master
