server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      override-system-properties: true
      server:
        native:
          search-locations:
            classpath:/config

